### ISSUE TITLE
There was a problem posting your review.

### ISSUE THREAD

**Issue by aVitaliy** [quer/the-steam-awards#8]
Приветствую!
У меня возникла проблема. Я скачал новую версию сегодня. Добавил в main.js выполнение этих скриптов:

`modules.push(require('./modules/gameRecommend'));
modules.push(require('./modules/events/steamAwardNominateGame'));
`

Однако при добавлении обзора на игру, обзор не добавляется. Пишет в логе

`StaRXX
Connected to Steam.
websession start
created
{"success":true,"strError":"There was a problem posting your review."}
fjerenet
vote - 1 - start
vote - 1 - end
vote - 2 - start
vote - 2 - end
vote - 3 - start
vote - 3 - end
vote - 4 - start
vote - 4 - end
vote - 5 - start
vote - 5 - end
vote - 6 - start
vote - 6 - end
vote - 7 - start
vote - 7 - end
vote - 8 - start
vote - 8 - end
created
fjerenet
done!
Modules done
done!
`

**Comment by quer** [comment]
Hey! thanks for using the script.
it is because you havent played dota 2(app 570) for at least 5 min. if all your account, have the same game, and over 5min. you can chance the code, in file
`gameRecommend.js` line 1 
or in 
`steamAwardNominateGame` on line 4 and 58 and 66 and 87

if you only need the Recommend.
only run `modules.push(require('./modules/gameRecommend'));`,

**Comment by quer** [comment]
you might be right, i will look into it later.

**Comment by quer** [comment]
The only thing i can see, even when it calls `{"success":true,"strError":"There was a problem posting your review."}` it still get the review
